[[armor]]
id = 1001
name = "Armadura de cuero"
slot = "body"
min_defense = 2
max_defense = 6

[[armor]]
id = 1002
name = "Armadura de placas"
slot = "body"
min_defense = 15
max_defense = 30

[[armor]]
id = 1003
name = "Tunica azul"
slot = "body"
min_defense = 6
max_defense = 10

[[armor]]
id = 2001
name = "Capucha"
slot = "helmet"
min_defense = 1
max_defense = 4

[[armor]]
id = 2002
name = "Casco de hierro"
slot = "helmet"
min_defense = 4
max_defense = 8

[[armor]]
id = 2003
name = "Sombrero magico"
slot = "helmet"
min_defense = 4
max_defense = 12

[[armor]]
id = 3001
name = "Escudo de tortuga"
slot = "shield"
min_defense = 1
max_defense = 2

[[armor]]
id = 3002
name = "Escudo de hierro"
slot = "shield"
min_defense = 1
max_defense = 4
