# =========================
# ARMORS - 1000 a 1999
# --- body 1001 a 1009
# --- helmet 1010 a 1019
# --- shield 1020 a 1029
# =========================

[[armor]]
id = 1000
name = "Armadura de cuero"
price = 150
slot = "body"
min_defense = 2
max_defense = 6

[[armor]]
id = 1001
name = "Armadura de placas"
price = 500
slot = "body"
min_defense = 15
max_defense = 30

[[armor]]
id = 1002
name = "Tunica azul"
price = 200
slot = "body"
min_defense = 6
max_defense = 10

[[armor]]
id = 1010
name = "Capucha"
price = 50
slot = "helmet"
min_defense = 1
max_defense = 4

[[armor]]
id = 1011
name = "Casco de hierro"
price = 100
slot = "helmet"
min_defense = 4
max_defense = 8

[[armor]]
id = 1012
name = "Sombrero magico"
price = 300
slot = "helmet"
min_defense = 4
max_defense = 12

[[armor]]
id = 1020
name = "Escudo de tortuga"
price = 80
slot = "shield"
min_defense = 1
max_defense = 2

[[armor]]
id = 1021
name = "Escudo de hierro"
price = 150
slot = "shield"
min_defense = 1
max_defense = 4

# =========================
# WEAPONS - 2000 a 2999
# --- melee 2000 a 2009
# --- ranged 2010 a 2019
# --- magic 2020 a 2029
# =========================

[[weapon]]
id = 2000
name = "Espada"
price = 100
min_damage = 2
max_damage = 5
type = "melee"
attack_range = 1
mana_cost = 0

[[weapon]]
id = 2001
name = "Hacha"
price = 120
min_damage = 4
max_damage = 5
type = "melee"
attack_range = 1
mana_cost = 0

[[weapon]]
id = 2002
name = "Martillo"
price = 150
min_damage = 1
max_damage = 9
type = "melee"
attack_range = 1
mana_cost = 0

[[weapon]]
id = 2010
name = "Arco simple"
price = 80
min_damage = 1
max_damage = 4
type = "ranged"
attack_range = 8
mana_cost = 0

[[weapon]]
id = 2011
name = "Arco compuesto"
price = 200
min_damage = 4
max_damage = 16
type = "ranged"
attack_range = 8
mana_cost = 0

[[weapon]]
id = 2020
name = "Vara de fresno"
price = 120
min_damage = 2
max_damage = 4
type = "magic"
attack_range = 8
mana_cost = 5

[[weapon]]
id = 2021
name = "Flauta elfica"
price = 180
min_damage = 0
max_damage = 0
type = "magic"
attack_range = 8
mana_cost = 100

[[weapon]]
id = 2022
name = "Baculo nudoso"
price = 200
min_damage = 4
max_damage = 8
type = "magic"
attack_range = 8
mana_cost = 15

[[weapon]]
id = 2023
name = "Baculo engarzado"
price = 300
min_damage = 8
max_damage = 20
type = "magic"
attack_range = 8
mana_cost = 30

# =========================
# CONSUMABLE - 3000 a 3999
# --- health 3000 a 3009
# --- mana 3010 a 3019
# --- strentgh 3020 a 3029
# --- agility 3030 a 3039
# =========================

[[consumable]]
id = 3000
name = "pocima de Mana"
price = 50
type = "mana"
durationMs = 0
effectValue = 10

[[consumable]]
id = 3010
name = "pocima de vida"
price = 50
type = "health"
durationMs = 0
effectValue = 10

[[consumable]]
id = 3020
name = "pocima de fuerza"
price = 50
type = "boostStr"
durationMs = 60000
effectValue = 10

[[consumable]]
id = 3030
name = "pocima de agilidad"
price = 50
type = "boostAgi"
durationMs = 60000
effectValue = 10
