# =========================
# MONSTERS
# =========================

[monsters]

[monsters.goblin]
max_health = 45
strength = 1
agility = 8
attack_min = 5
attack_max = 12
detection_range = 6
attack_range = 1
zone = "forest"
min_level = 1
max_level = 20
attack_cooldown_ms = 1200
move_cooldown_ms = 600

[monsters.skeleton]
max_health = 70
strength = 1
agility = 5
attack_min = 10
attack_max = 20
detection_range = 6
attack_range = 1
zone = "desert"
min_level = 5
max_level = 30
attack_cooldown_ms = 1500
move_cooldown_ms = 700

[monsters.zombie]
max_health = 90
strength = 1
agility = 2
attack_min = 15
attack_max = 25
detection_range = 5
attack_range = 1
zone = "normal"
min_level = 5
max_level = 30
attack_cooldown_ms = 2000
move_cooldown_ms = 1000

[monsters.spider]
max_health = 40
strength = 1
agility = 10
attack_min = 6
attack_max = 15
detection_range = 7
attack_range = 1
zone = "forest"
min_level = 1
max_level = 20
attack_cooldown_ms = 900
move_cooldown_ms = 500

[monsters.orc]
max_health = 150
strength = 1
agility = 4
attack_min = 20
attack_max = 35
detection_range = 6
attack_range = 1
zone = "normal"
min_level = 15
max_level = 40
attack_cooldown_ms = 1800
move_cooldown_ms = 800

[monsters.golem]
max_health = 300
strength = 1
agility = 1
attack_min = 40
attack_max = 65
detection_range = 4
attack_range = 1
zone = "desert"
min_level = 20
max_level = 50
attack_cooldown_ms = 3000
move_cooldown_ms = 1200

[monsters.boss_balrog]
max_health = 3000
strength = 1
agility = 8
attack_min = 176
attack_max = 264
detection_range = 8
attack_range = 1
min_level = 35
max_level = 45
zone = "dungeon"
attack_cooldown_ms = 1500
move_cooldown_ms = 1000
is_boss = true
unique_drop_item_id = 4002
guaranteed_gold = 500
extra_loot = [3000, 3010, 3020]

[monsters.boss_titan]
max_health = 4000
strength = 1
agility = 3
attack_min = 270
attack_max = 378
detection_range = 6
attack_range = 1
min_level = 45
max_level = 60
zone = "dungeon"
attack_cooldown_ms = 2500
move_cooldown_ms = 1200
is_boss = true
unique_drop_item_id = 4001
guaranteed_gold = 700
extra_loot = [3010, 3010, 3020]

[monsters.boss_coloso]
max_health = 3500
strength = 1
agility = 4
attack_min = 196
attack_max = 294
detection_range = 7
attack_range = 1
min_level = 40
max_level = 50
zone = "dungeon"
attack_cooldown_ms = 2000
move_cooldown_ms = 1100
is_boss = true
unique_drop_item_id = 4003
guaranteed_gold = 600
extra_loot = [3010, 3020]

[monsters.boss_aracne]
max_health = 2000
strength = 1
agility = 15
attack_min = 85
attack_max = 170
detection_range = 12
attack_range = 1
min_level = 25
max_level = 35
zone = "dungeon"
attack_cooldown_ms = 1000
move_cooldown_ms = 700
is_boss = true
unique_drop_item_id = 4004
guaranteed_gold = 300
extra_loot = [3030, 3030]
